url: https://trellisframework.net
enforce_ssl: trellisframework.net

# Theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Site settings
title: Trellis Framework
description: A comprehensive Java framework for building enterprise microservices